"""add last_chat_id to user table.

Revision ID: a9b79af35eae
Revises: 61f24b4c2453
Create Date: 2026-03-08 10:33:33.947726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b79af35eae'
down_revision: Union[str, Sequence[str], None] = '61f24b4c2453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_chat_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_chat_id')
    # ### end Alembic commands ###
